@echo off
REM ===============================================================================
REM InstaMakaan - Automated Setup Script for Windows
REM This script sets up the entire InstaMakaan application locally
REM ===============================================================================

setlocal enabledelayedexpansion

REM Configuration
set MONGO_URL=mongodb://localhost:27017
set DB_NAME=instamakaan
set BACKEND_PORT=8001
set FRONTEND_PORT=3000

REM Colors (Windows 10+)
set "GREEN=[32m"
set "RED=[31m"
set "YELLOW=[33m"
set "CYAN=[36m"
set "NC=[0m"

echo.
echo %CYAN%  ╦┌┐┌┌─┐┌┬┐┌─┐╔╦╗┌─┐┬┌─┌─┐┌─┐┌┐┌%NC%
echo %CYAN%  ║│││└─┐ │ ├─┤║║║├─┤├┴┐├─┤├─┤│││%NC%
echo %CYAN%  ╩┘└┘└─┘ ┴ ┴ ┴╩ ╩┴ ┴┴ ┴┴ ┴┴ ┴┘└┘%NC%
echo.
echo   Automated Setup Script for Windows v1.0
echo.

REM ===============================================================================
REM Check Prerequisites
REM ===============================================================================

echo %CYAN%╔════════════════════════════════════════════════════════════════╗%NC%
echo %CYAN%║  Checking Prerequisites                                        ║%NC%
echo %CYAN%╚════════════════════════════════════════════════════════════════╝%NC%
echo.

REM Check Node.js
echo [*] Checking Node.js...
where node >nul 2>&1
if %errorlevel% neq 0 (
    echo %RED%[X] Node.js not found. Please install from https://nodejs.org/%NC%
    goto :error
)
for /f "tokens=*" %%i in ('node --version') do set NODE_VERSION=%%i
echo %GREEN%[OK] Node.js found: %NODE_VERSION%%NC%

REM Check Yarn
echo [*] Checking Yarn...
where yarn >nul 2>&1
if %errorlevel% neq 0 (
    echo %YELLOW%[!] Yarn not found. Installing via npm...%NC%
    npm install -g yarn
)
for /f "tokens=*" %%i in ('yarn --version') do set YARN_VERSION=%%i
echo %GREEN%[OK] Yarn found: %YARN_VERSION%%NC%

REM Check Python
echo [*] Checking Python...
where python >nul 2>&1
if %errorlevel% neq 0 (
    echo %RED%[X] Python not found. Please install from https://python.org/%NC%
    goto :error
)
for /f "tokens=*" %%i in ('python --version') do set PYTHON_VERSION=%%i
echo %GREEN%[OK] Python found: %PYTHON_VERSION%%NC%

echo.
echo %GREEN%[OK] All prerequisites satisfied!%NC%
echo.

REM ===============================================================================
REM Setup Backend
REM ===============================================================================

echo %CYAN%╔════════════════════════════════════════════════════════════════╗%NC%
echo %CYAN%║  Setting Up Backend                                            ║%NC%
echo %CYAN%╚════════════════════════════════════════════════════════════════╝%NC%
echo.

cd backend

REM Create virtual environment
echo [*] Creating Python virtual environment...
if not exist "venv" (
    python -m venv venv
    echo %GREEN%[OK] Virtual environment created%NC%
) else (
    echo [i] Virtual environment already exists
)

REM Activate and install dependencies
echo [*] Installing Python dependencies...
call venv\Scripts\activate.bat
python -m pip install --upgrade pip -q
pip install -r requirements.txt -q
echo %GREEN%[OK] Python dependencies installed%NC%

REM Create .env file
echo [*] Creating backend .env file...
(
echo # InstaMakaan Backend Configuration
echo # Generated by setup script
echo.
echo # MongoDB Configuration
echo MONGO_URL="%MONGO_URL%"
echo DB_NAME="%DB_NAME%"
echo.
echo # CORS Configuration
echo CORS_ORIGINS="http://localhost:%FRONTEND_PORT%,http://127.0.0.1:%FRONTEND_PORT%"
echo.
echo # JWT Configuration
echo JWT_SECRET="instamakaan-super-secret-key-change-in-production"
echo JWT_ALGORITHM="HS256"
echo ACCESS_TOKEN_EXPIRE_MINUTES=30
) > .env
echo %GREEN%[OK] Backend .env file created%NC%

cd ..
echo.
echo %GREEN%[OK] Backend setup complete!%NC%
echo.

REM ===============================================================================
REM Setup Frontend
REM ===============================================================================

echo %CYAN%╔════════════════════════════════════════════════════════════════╗%NC%
echo %CYAN%║  Setting Up Frontend                                           ║%NC%
echo %CYAN%╚════════════════════════════════════════════════════════════════╝%NC%
echo.

cd frontend

REM Install dependencies
echo [*] Installing Node.js dependencies (this may take a few minutes)...
call yarn install --silent
echo %GREEN%[OK] Node.js dependencies installed%NC%

REM Create .env file
echo [*] Creating frontend .env file...
(
echo # InstaMakaan Frontend Configuration
echo # Generated by setup script
echo.
echo # Backend API URL
echo REACT_APP_BACKEND_URL=http://localhost:%BACKEND_PORT%
echo.
echo # WebSocket port
echo WDS_SOCKET_PORT=
echo.
echo # Health check
echo ENABLE_HEALTH_CHECK=false
) > .env
echo %GREEN%[OK] Frontend .env file created%NC%

cd ..
echo.
echo %GREEN%[OK] Frontend setup complete!%NC%
echo.

REM ===============================================================================
REM Seed Database
REM ===============================================================================

echo %CYAN%╔════════════════════════════════════════════════════════════════╗%NC%
echo %CYAN%║  Seeding Database                                              ║%NC%
echo %CYAN%╚════════════════════════════════════════════════════════════════╝%NC%
echo.

cd backend
call venv\Scripts\activate.bat
echo [*] Running database seed script...
python seed_data.py
cd ..
echo.

REM ===============================================================================
REM Create Start Scripts
REM ===============================================================================

echo %CYAN%╔════════════════════════════════════════════════════════════════╗%NC%
echo %CYAN%║  Creating Start Scripts                                        ║%NC%
echo %CYAN%╚════════════════════════════════════════════════════════════════╝%NC%
echo.

REM Create start-backend.bat
echo [*] Creating start-backend.bat...
(
echo @echo off
echo cd /d "%%~dp0backend"
echo call venv\Scripts\activate.bat
echo echo Starting InstaMakaan Backend on port 8001...
echo uvicorn server:app --host 0.0.0.0 --port 8001 --reload
) > start-backend.bat
echo %GREEN%[OK] start-backend.bat created%NC%

REM Create start-frontend.bat
echo [*] Creating start-frontend.bat...
(
echo @echo off
echo cd /d "%%~dp0frontend"
echo echo Starting InstaMakaan Frontend on port 3000...
echo yarn start
) > start-frontend.bat
echo %GREEN%[OK] start-frontend.bat created%NC%

REM Create start-all.bat
echo [*] Creating start-all.bat...
(
echo @echo off
echo echo Starting InstaMakaan Application...
echo echo.
echo echo Starting Backend in new window...
echo start "InstaMakaan Backend" cmd /k "cd /d %%~dp0backend && call venv\Scripts\activate.bat && uvicorn server:app --host 0.0.0.0 --port 8001 --reload"
echo timeout /t 3 /nobreak ^>nul
echo echo Starting Frontend in new window...
echo start "InstaMakaan Frontend" cmd /k "cd /d %%~dp0frontend && yarn start"
echo echo.
echo echo ╔════════════════════════════════════════════════════════════════╗
echo echo ║  InstaMakaan is starting...                                    ║
echo echo ╠════════════════════════════════════════════════════════════════╣
echo echo ║  Frontend:    http://localhost:3000                            ║
echo echo ║  Admin Panel: http://localhost:3000/admin                      ║
echo echo ║  Backend API: http://localhost:8001/api                        ║
echo echo ║  API Docs:    http://localhost:8001/docs                       ║
echo echo ╚════════════════════════════════════════════════════════════════╝
echo echo.
echo echo Close the Backend and Frontend windows to stop the services.
) > start-all.bat
echo %GREEN%[OK] start-all.bat created%NC%

echo.
echo %GREEN%[OK] All start scripts created!%NC%
echo.

REM ===============================================================================
REM Final Instructions
REM ===============================================================================

echo.
echo %GREEN%╔════════════════════════════════════════════════════════════════╗%NC%
echo %GREEN%║                                                                ║%NC%
echo %GREEN%║   🎉  InstaMakaan Setup Complete!                              ║%NC%
echo %GREEN%║                                                                ║%NC%
echo %GREEN%╚════════════════════════════════════════════════════════════════╝%NC%
echo.
echo %CYAN%Quick Start Commands:%NC%
echo.
echo   %YELLOW%Start everything:%NC%
echo     start-all.bat
echo.
echo   %YELLOW%Or start services separately:%NC%
echo     Terminal 1: start-backend.bat
echo     Terminal 2: start-frontend.bat
echo.
echo %CYAN%Access Points:%NC%
echo.
echo   Frontend:     http://localhost:3000
echo   Admin Panel:  http://localhost:3000/admin
echo   Backend API:  http://localhost:8001/api
echo   API Docs:     http://localhost:8001/docs
echo.
echo %CYAN%Sample Data Created:%NC%
echo.
echo   * 3 Property Owners
echo   * 3 Agents
echo   * 5 Properties (rent, buy, pre-occupied)
echo   * 4 Inquiries with conversation logs
echo.
echo %CYAN%NOTE: Make sure MongoDB is running before starting the application!%NC%
echo.
echo Happy coding! 
echo.
goto :end

:error
echo.
echo %RED%Setup failed. Please fix the errors above and try again.%NC%
echo.
exit /b 1

:end
endlocal
