import React from 'react';
import { Lightbulb } from 'lucide-react';

/**
 * InsightsPanel
 * Displays a list of dynamic financial insights generated by the services.
 */
export const InsightsPanel = ({ insights }) => {
  if (!insights || insights.length === 0) return null;

  return (
    <div className="bg-amber-50/50 dark:bg-amber-900/10 border border-amber-200 dark:border-amber-800/30 rounded-2xl p-5 md:p-6 mb-6">
      <div className="flex items-center gap-2 mb-4">
        <Lightbulb className="w-5 h-5 text-amber-500" />
        <h3 className="text-lg font-bold text-gray-900 dark:text-amber-50">Financial Insights</h3>
      </div>
      <ul className="space-y-3">
        {insights.map((insight, index) => (
          <li key={index} className="flex items-start gap-3">
            <div className="w-1.5 h-1.5 rounded-full bg-amber-400 mt-2 shrink-0" />
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed text-sm md:text-base">
              <span dangerouslySetInnerHTML={{ __html: insight }} />
            </p>
          </li>
        ))}
      </ul>
    </div>
  );
};
